buy_me_a_coffee: danceworldtv
custom:
  - https://finance.ozon.ru/apps/sbp/ozonbankpay/019a0a87-1f4a-7df8-97c7-ef32ebf9a0e3
  - https://paypal.me/imiked
  - https://boosty.to/danceworldtv/donate
  - VISA: 4400430236422744;
  - USDT Ethereum (ERC20): 0xBd0593dDF1DFC7fD95bB6F4e6A5c73Da44048B40;
  - USDT TON: UQCr2Fp7t34QFuO4IesN3Lo3186a93Z1B7Wu76imr6APIXgk;
  - USDT Tron (TRC20): TE5A3GT84eJ9iT3mYYLv1KXJnMaiZFxNuA.
